# Generated by Django 5.2 on 2025-05-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedGuardApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
